### PR TITLE
Allow running unprivileged, including from Apptainer

### PR DESCRIPTION
**Pull request by DrDaveD**
This PR has changes to the base container that enable running the frontier-squid container (with additional changes I will submit later) as an unprivileged user from Apptainer.

### CODE REVIEW

**Comment by DrDaveD** [comment]
@matyasselmeci @brianhlin Please review

**Comment by matyasselmeci** [comment]
If I try to run this as a nonzero user (with podman), supervisord dies with
```
PermissionError: [Errno 13] Permission denied: '/var/log/supervisord.log'
```
any ideas?

**Comment by DrDaveD** [comment]
@holzman was having the same type of error with trying it for use on OKD.  He was going to try to change the permissions on /var/log to be writable by the unprivileged user, but otherwise, couldn't you bind-mount in a writable directory for /var/log?

With apptainer I don't have the problem because I use it with `--writable-tmpfs` and the underlying files look like they are owned by the unprivileged user.

**Comment by DrDaveD** [comment]
Check the crond output in /var/log/supervisord.

I don't see any point to trying to make it work with a nonzero user in podman since works with the default, zero user.  Apparently OKD does not allow running a container as a pseudo-root user, which doesn't make much sense to me but if we can make it work that would be good.  My goal was to make it work with unprivileged apptainer which has only one user id to work with, usually the original unprivileged user.

**Comment by holzman** [comment]
I forgot to specify, but the above test was with Docker on my desktop, not podman. (To be clear, OpenShift/OKD do not use podman but use cri-o).

I wouldn't call GID 0 pseudo-root, but also to be clear: this is an OpenShift/OKD configuration, it does not have to do with podman or cri-o.  The GID is just a way to manage file permissions for ephemeral users without root.

I did take a look at the logs: `/var/run` also needs to be writable by the user running the container.  Once I changed those permissions, it does run.

**Comment by DrDaveD** [comment]
Ok I added a commit that works for me to run also with `podman run -u $(id -u)`.  Does it look ok @holzman?

**Comment by holzman** [comment]
Works for me, thanks @DrDaveD!

```[burt@baz test]$ oc logs pod/burt-cpu-test
2023-05-19 20:02:47,907 INFO Included extra file "/etc/supervisord.d/00-cleanup.conf" during parsing
2023-05-19 20:02:47,907 INFO Set uid to user 1000880000 succeeded
2023-05-19 20:02:47,911 INFO RPC interface 'supervisor' initialized
2023-05-19 20:02:47,911 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2023-05-19 20:02:47,912 INFO supervisord started with pid 1
2023-05-19 20:02:48,918 INFO spawned: 'container_cleanup' with pid 11
2023-05-19 20:02:48,926 INFO spawned: 'crond' with pid 12
2023-05-19 20:02:49,929 INFO success: container_cleanup entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-05-19 20:02:49,930 INFO success: crond entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Review by matyasselmeci — APPROVED** [review]
LGTM, though I do not want to merge it on a Friday afternoon. Thanks @DrDaveD and @holzman!

**Pull request merged**
