### PR TITLE
add fetch-crl cron that works in docker

### PR DESCRIPTION
**Pull request by ddavila0**

### CODE REVIEW

**Review by brianhlin — COMMENTED** [review]
This LGTM except we should add `fetch-crl` to the yum install list above, too

**Comment by ddavila0** [comment]
Yeah, I thought about it, but that won't make the cron job to work anyways, unless we add also some CA certs in /etc/grid-security/certificates. 
@brianhlin do you want me to add both fetch-crl and osg-ca-certs +  osg-ca-certs-updater ? or just fetch-crl?

**Comment by brianhlin** [comment]
Yeah, let's add `fetch-crl` and `osg-ca-certs`. We can skip `osg-ca-certs-updater` because we rebuild the base with each OSG release

**Review by brianhlin — APPROVED** [review]
LGTM

**Pull request merged**
