### PR TITLE
Give fetch-crl a short leash

### PR DESCRIPTION
**Pull request by brianhlin**
Default timeout is 120 seconds

Am I missing any other aggressive settings @jthiltges ?

### CODE REVIEW

**Comment by matyasselmeci** [comment]
Why does this help?

**Comment by matyasselmeci** [comment]
If you want to help with the low memory problem maybe cut the parallelism (the -p 5). A ten second timeout is fine; we can bump it if we see too many failures.

**Comment by brianhlin** [comment]
We haven't seen problems elsewhere so I'm not too worried about that parallelism – I bumped the memory assigned to the affected containers instead

**Review by matyasselmeci — APPROVED** [review]

**Comment by matyasselmeci** [comment]
🤷🏻 I guess we'll see

**Pull request merged**
